### ISSUE TITLE
API for accessing data

### ISSUE THREAD

**Issue by connor642** [radiowarwick/digiplay-laravel#42]
Would return JSON data. Probably look into using [this](https://packagist.org/packages/chrisbjr/api-guard) library for protecting the requests.

Data that would be accessible could for instance be:
- Song log (with a param for each studio id/name)
- Song data querying
- Song searching
- Messages to studio
- Shows (once space is migrated)
- Equipment bookings (once space is migrated)
- Anything else that may be useful

**Comment by connor642** [comment]
Also to add maybe add a new "Application" model/table to store the data and keys

**Comment by willllhallll** [comment]
To confirm, does the [api-guard](https://packagist.org/packages/chrisbjr/api-guard) package work by assigning pre-generated keys to clients, more like a client secret rather than a bearer token?

For example, if I had an application server that wanted to access this API, would I have to manually generate an API key using some CLI command on the Digiplay server, then copy and store it locally on the application server, later passing it to the Digiplay API with every request?

Sort of a 'whitelist' of possible clients?

**Comment by connor642** [comment]
I have no idea, I've not really looked into, I'm assuming there's methods to generate keys, so there could be an admin interface to generate "Application" models which has an an attirubte/row with they key, there might be other api libraries out there though.

I suppose by doing that there would then be a whitelist of clients/applications with their appropriate keys.

**Comment by connor642** [comment]
So reading more into the docs for api-guard we could create an `Application` model/class which implements the `Apikeyable` trait. So using these together there's methods to generate and attach keys to a model. Still not 100% sure if we should go with this or could just create our own middleware

**Comment by connor642** [comment]
I just read [this](http://www.jeffreyteruel.com/article/22) article, might be easier to implement

**Comment by willllhallll** [comment]
So with the [above article](http://www.jeffreyteruel.com/article/22), it looks like each existing user would receive an access key (generated by us) and this key would be used in each request to the API. One would be made for each entry into the `web_members` table. 

My big question is: does the API even need to be secured? Will we be serving any sensitive data? If yes,  then would it make sense to have un-guessable keys for each RAW member ([above article](http://www.jeffreyteruel.com/article/22)), or instead maintain a whitelist of un-guessable keys (that some admin could control / generate new ones for new projects) using an application model ([api-guard](https://packagist.org/packages/chrisbjr/api-guard))?

![BestAPI](https://user-images.githubusercontent.com/29780384/54378264-daab6500-467e-11e9-9341-e8ece9721538.jpg)

**I vote option D**

**Comment by connor642** [comment]
So the `web_members` table is part of the Space database. I'm thinking of a new `application` table and models in Digiplay database and then have a long, random key for each application, where Admin users can create new Applications which will generate keys at the same time.

I think definitely use API keys as we don't want to leak sensitive data (names of people booking equipment for instance), and writing the middleware for that won't be too difficult. I'm happy to write all that side of things

**Comment by willllhallll** [comment]
I gotcha! That sounds awesome.

To get to better grips with Lavarel and such, could I have a go at writing the front-end of the API key control panel for Admins (using those neat Blade templates)? Will spin up a local environment using Homestead.

My dreams of a real actual RAW API could be coming true...  (cough *[space/services](https://space.radio.warwick.ac.uk/services/public/)* cough)

**Comment by willllhallll** [comment]
Love the first few endpoints. Great to use them. 

I just have one feature request: 

Would it be possible to include some unique ID with each piece of data / row returned (e.g. primary key from table)? 

The reason being that (whilst potentially rare) there may be some collisions when two data rows are identical and this could cause bugs when trying to compare this data programmatically.

EDIT: My main reason for requesting this is during UI updates with React. Each component requires a unique ID so that React can track changes and decide whether a re-render. 

Usually, this unique ID is derived from the data that feeds the application, or (for lists of components and as a last resort) the index of the component in a list. 

However, the index cannot be used to track changes if the data changes independently to the index. This is the case with this API, and so a unique ID would be much appreciated. 

RESOLVED: https://github.com/radiowarwick/digiplay-laravel/pull/48
